[package]
name = "git-host"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait.workspace = true
backon.workspace = true
chrono.workspace = true
db.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
ts-rs.workspace = true
url.workspace = true
utils.workspace = true
