// This file was auto-generated by generate_types in the remote crate.
// Do not edit manually.

// Electric row types
export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export type Project = { id: string, name: string, color: string, sort_order: number, parent_id: string | null, has_orchestrator_prompt: boolean, created_at: string, updated_at: string, };

export type Workspace = { id: string, project_id: string, issue_id: string | null, local_workspace_id: string | null, name: string | null, archived: boolean, files_changed: number | null, lines_added: number | null, lines_removed: number | null, created_at: string, updated_at: string, };

export type ProjectStatus = { id: string, project_id: string, name: string, color: string, sort_order: number, hidden: boolean, created_at: string, };

export type Tag = { id: string, project_id: string, name: string, color: string, };

export type Issue = { id: string, project_id: string, issue_number: number, simple_id: string, status_id: string, title: string, description: string | null, priority: IssuePriority | null, start_date: string | null, target_date: string | null, completed_at: string | null, sort_order: number, parent_issue_id: string | null, parent_issue_sort_order: number | null, extension_metadata: JsonValue, created_at: string, updated_at: string, };

export type IssueTag = { id: string, issue_id: string, tag_id: string, };

export type IssueRelationship = { id: string, issue_id: string, related_issue_id: string, relationship_type: IssueRelationshipType, created_at: string, };

export type IssueRelationshipType = "blocking" | "related" | "has_duplicate";

export type IssueComment = { id: string, issue_id: string, parent_id: string | null, message: string, created_at: string, updated_at: string, };

export type IssuePriority = "urgent" | "high" | "medium" | "low";

export type IssueSortField = "sort_order" | "priority" | "created_at" | "updated_at" | "title";

export type ListIssuesQuery = { project_id: string, };

export type SearchIssuesRequest = { project_id: string, status_id?: string, status_ids?: Array<string>, priority?: IssuePriority, parent_issue_id?: string, search?: string, simple_id?: string, tag_id?: string, tag_ids?: Array<string>, sort_field?: IssueSortField, sort_direction?: SortDirection, limit?: number, offset?: number, };

export type ListIssuesResponse = { issues: Array<Issue>, total_count: number, limit: number, offset: number, };

export type PullRequestStatus = "open" | "merged" | "closed";

export type PullRequest = { id: string, url: string, number: number, status: PullRequestStatus, merged_at: string | null, merge_commit_sha: string | null, target_branch_name: string, project_id: string, issue_id: string, workspace_id: string | null, created_at: string, updated_at: string, };

export type PullRequestIssue = { id: string, pull_request_id: string, issue_id: string, };

export type CreatePullRequestIssueRequest = {
 /**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, issue_id: string, url: string, number: number, status: PullRequestStatus, merged_at: string | null, merge_commit_sha: string | null, target_branch_name: string, };

export type SortDirection = "asc" | "desc";

export type CreateRemoteSessionResponse = { session_id: string, };

export type CreateProjectRequest = {
 /**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, name: string, color: string, parent_id?: string | null, };

export type UpdateProjectRequest = { name: string | null, color: string | null, sort_order: number | null, parent_id?: string | null, };

export type CreateTagRequest = {
 /**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, project_id: string, name: string, color: string, };

export type UpdateTagRequest = { name: string | null, color: string | null, };

export type CreateProjectStatusRequest = {
 /**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, project_id: string, name: string, color: string, sort_order: number, hidden: boolean, };

export type UpdateProjectStatusRequest = { name: string | null, color: string | null, sort_order: number | null, hidden: boolean | null, };

export type CreateIssueRequest = {
 /**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, project_id: string, status_id: string, title: string, description: string | null, priority: IssuePriority | null, start_date: string | null, target_date: string | null, completed_at: string | null, sort_order: number, parent_issue_id: string | null, parent_issue_sort_order: number | null, extension_metadata: JsonValue, };

export type UpdateIssueRequest = { status_id?: string | null, title?: string | null, description?: string | null | null, priority?: IssuePriority | null | null, start_date?: string | null | null, target_date?: string | null | null, completed_at?: string | null | null, sort_order?: number | null, parent_issue_id?: string | null | null, parent_issue_sort_order?: number | null | null, extension_metadata?: JsonValue | null, };

export type CreateIssueTagRequest = {
 /**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, issue_id: string, tag_id: string, };

export type CreateIssueRelationshipRequest = {
 /**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, issue_id: string, related_issue_id: string, relationship_type: IssueRelationshipType, };

export type CreateIssueCommentRequest = {
 /**
 * Optional client-generated ID. If not provided, server generates one.
 * Using client-generated IDs enables stable optimistic updates.
 */
id?: string, issue_id: string, message: string, parent_id: string | null, };

export type UpdateIssueCommentRequest = { message: string | null, parent_id: string | null | null, };

export type ExportRequest = {
/**
 * If empty, exports all projects.
 */
project_ids: Array<string>, include_attachments: boolean, };

// Shape definition interface
export interface ShapeDefinition<T> {
  readonly table: string;
  readonly params: readonly string[];
  readonly url: string;
  readonly fallbackUrl: string;
  readonly _type: T;  // Phantom field for type inference (not present at runtime)
}

// Helper to create type-safe shape definitions
function defineShape<T>(
  table: string,
  params: readonly string[],
  url: string,
  fallbackUrl: string
): ShapeDefinition<T> {
  return { table, params, url, fallbackUrl } as ShapeDefinition<T>;
}

// Individual shape definitions with embedded types
export const PROJECTS_SHAPE = defineShape<Project>(
  'projects',
  [] as const,
  '/v1/shape/projects',
  '/v1/fallback/projects'
);

export const PROJECT_TAGS_SHAPE = defineShape<Tag>(
  'tags',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/tags',
  '/v1/fallback/tags'
);

export const PROJECT_PROJECT_STATUSES_SHAPE = defineShape<ProjectStatus>(
  'project_statuses',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/project_statuses',
  '/v1/fallback/project_statuses'
);

export const PROJECT_ISSUES_SHAPE = defineShape<Issue>(
  'issues',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/issues',
  '/v1/fallback/issues'
);

export const WORKSPACES_SHAPE = defineShape<Workspace>(
  'workspaces',
  [] as const,
  '/v1/shape/workspaces',
  '/v1/fallback/workspaces'
);

export const PROJECT_WORKSPACES_SHAPE = defineShape<Workspace>(
  'workspaces',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/workspaces',
  '/v1/fallback/project_workspaces'
);

export const PROJECT_ISSUE_TAGS_SHAPE = defineShape<IssueTag>(
  'issue_tags',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/issue_tags',
  '/v1/fallback/issue_tags'
);

export const PROJECT_ISSUE_RELATIONSHIPS_SHAPE = defineShape<IssueRelationship>(
  'issue_relationships',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/issue_relationships',
  '/v1/fallback/issue_relationships'
);

export const PROJECT_PULL_REQUESTS_SHAPE = defineShape<PullRequest>(
  'pull_requests',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/pull_requests',
  '/v1/fallback/pull_requests'
);

export const PROJECT_PULL_REQUEST_ISSUES_SHAPE = defineShape<PullRequestIssue>(
  'pull_request_issues',
  ['project_id'] as const,
  '/v1/shape/project/{project_id}/pull_request_issues',
  '/v1/fallback/pull_request_issues'
);

export const ISSUE_COMMENTS_SHAPE = defineShape<IssueComment>(
  'issue_comments',
  ['issue_id'] as const,
  '/v1/shape/issue/{issue_id}/comments',
  '/v1/fallback/issue_comments'
);

// =============================================================================
// Mutation Definitions
// =============================================================================

// Mutation definition interface
export interface MutationDefinition<TRow, TCreate = unknown, TUpdate = unknown> {
  readonly name: string;
  readonly url: string;
  readonly _rowType: TRow;  // Phantom field for type inference (not present at runtime)
  readonly _createType: TCreate;  // Phantom field for type inference (not present at runtime)
  readonly _updateType: TUpdate;  // Phantom field for type inference (not present at runtime)
}

// Helper to create type-safe mutation definitions
function defineMutation<TRow, TCreate, TUpdate>(
  name: string,
  url: string
): MutationDefinition<TRow, TCreate, TUpdate> {
  return { name, url } as MutationDefinition<TRow, TCreate, TUpdate>;
}

// Individual mutation definitions
export const PROJECT_MUTATION = defineMutation<Project, CreateProjectRequest, UpdateProjectRequest>(
  'Project',
  '/v1/projects'
);

export const TAG_MUTATION = defineMutation<Tag, CreateTagRequest, UpdateTagRequest>(
  'Tag',
  '/v1/tags'
);

export const PROJECT_STATUS_MUTATION = defineMutation<ProjectStatus, CreateProjectStatusRequest, UpdateProjectStatusRequest>(
  'ProjectStatus',
  '/v1/project_statuses'
);

export const ISSUE_MUTATION = defineMutation<Issue, CreateIssueRequest, UpdateIssueRequest>(
  'Issue',
  '/v1/issues'
);

export const ISSUE_TAG_MUTATION = defineMutation<IssueTag, CreateIssueTagRequest, unknown>(
  'IssueTag',
  '/v1/issue_tags'
);

export const ISSUE_RELATIONSHIP_MUTATION = defineMutation<IssueRelationship, CreateIssueRelationshipRequest, unknown>(
  'IssueRelationship',
  '/v1/issue_relationships'
);

export const ISSUE_COMMENT_MUTATION = defineMutation<IssueComment, CreateIssueCommentRequest, UpdateIssueCommentRequest>(
  'IssueComment',
  '/v1/issue_comments'
);

export const PULL_REQUEST_ISSUE_MUTATION = defineMutation<PullRequestIssue, CreatePullRequestIssueRequest, unknown>(
  'PullRequestIssue',
  '/v1/pull_request_issues'
);

// Type helpers to extract types from a mutation definition
export type MutationRowType<M extends MutationDefinition<unknown>> = M extends MutationDefinition<infer R> ? R : never;
export type MutationCreateType<M extends MutationDefinition<unknown, unknown>> = M extends MutationDefinition<unknown, infer C> ? C : never;
export type MutationUpdateType<M extends MutationDefinition<unknown, unknown, unknown>> = M extends MutationDefinition<unknown, unknown, infer U> ? U : never;
