// This file was generated by `crates/core/src/bin/generate_types.rs`.

// Do not edit this file manually.

// If you are an AI, and you absolutely have to edit this file, please confirm with the user first.

export type Repo = { id: string, path: string, name: string, display_name: string, setup_script: string | null, cleanup_script: string | null, archive_script: string | null, copy_files: string | null, parallel_setup_script: boolean, dev_server_script: string | null, default_target_branch: string | null, default_working_dir: string | null, created_at: Date, updated_at: Date, };

export type Project = { id: string, name: string, 
/**
 * Per-project issue prefix (e.g. "ACME" -> "ACME-5"). Defaults from name.
 */
key: string | null, color: string, sort_order: bigint, parent_id: string | null, default_agent_working_dir: string | null, remote_project_id: string | null, 
/**
 * ADR-016: per-project / per-board orchestrator prompt. Empty string =
 * "no prompt at this scope"; resolution walks the parent chain and
 * composes every non-empty value into a labeled stack (board-first /
 * project-last). UPGRADE-SAFE: the migration sets DEFAULT '' so
 * existing rows are valid without rewrite.
 */
orchestrator_prompt: string, created_at: Date, updated_at: Date, };

export type UpdateRepo = { display_name?: string | null, setup_script?: string | null, cleanup_script?: string | null, archive_script?: string | null, copy_files?: string | null, parallel_setup_script?: boolean | null, dev_server_script?: string | null, default_target_branch?: string | null, default_working_dir?: string | null, };

export type SearchResult = { path: string, is_file: boolean, match_type: SearchMatchType, 
/**
 * Ranking score based on git history (higher = more recently/frequently edited)
 */
score: bigint, };

export type SearchMatchType = "FileName" | "DirectoryName" | "FullPath";

export type WorkspaceRepo = { id: string, workspace_id: string, repo_id: string, target_branch: string, created_at: Date, updated_at: Date, };

export type CreateWorkspaceRepo = { repo_id: string, target_branch: string, };

export type RepoWithTargetBranch = { target_branch: string, id: string, path: string, name: string, display_name: string, setup_script: string | null, cleanup_script: string | null, archive_script: string | null, copy_files: string | null, parallel_setup_script: boolean, dev_server_script: string | null, default_target_branch: string | null, default_working_dir: string | null, created_at: Date, updated_at: Date, };

export type Tag = { id: string, tag_name: string, content: string, created_at: string, updated_at: string, };

export type CreateTag = { tag_name: string, content: string, };

export type UpdateTag = { tag_name: string | null, content: string | null, };

export type DraftFollowUpData = { message: string, executor_config: ExecutorConfig, };

export type DraftWorkspaceData = { message: string, repos: Array<DraftWorkspaceRepo>, executor_config: ExecutorConfig | null, linked_issue: DraftWorkspaceLinkedIssue | null, attachments: Array<DraftWorkspaceAttachment>, };

export type DraftWorkspaceAttachment = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, };

export type DraftWorkspaceLinkedIssue = { issue_id: string, simple_id: string, title: string, remote_project_id: string, };

export type DraftWorkspaceRepo = { repo_id: string, target_branch: string, };

export type DraftIssueData = { title: string, description: string | null, status_id: string, 
/**
 * Stored as the string value of IssuePriority (e.g. "urgent", "high", "medium", "low")
 */
priority: string | null, tag_ids: Array<string>, create_draft_workspace: boolean, 
/**
 * The project this draft belongs to
 */
project_id: string, 
/**
 * Parent issue ID if creating a sub-issue
 */
parent_issue_id: string | null, };

export type PreviewSettingsData = { url: string, screen_size: string | null, responsive_width: number | null, responsive_height: number | null, };

export type WorkspaceNotesData = { content: string, };

export type WorkspacePanelStateData = { right_main_panel_mode: string | null, is_left_main_panel_visible: boolean, };

export type WorkspacePrFilterData = "all" | "has_pr" | "no_pr";

export type WorkspaceSortByData = "updated_at" | "created_at";

export type WorkspaceSortOrderData = "asc" | "desc";

export type WorkspaceFilterStateData = { project_ids: Array<string>, pr_filter: WorkspacePrFilterData, };

export type WorkspaceSortStateData = { sort_by: WorkspaceSortByData, sort_order: WorkspaceSortOrderData, };

export type UiPreferencesData = { 
/**
 * Preferred repo actions per repo
 */
repo_actions: { [key in string]?: string }, 
/**
 * Expanded/collapsed state for UI sections
 */
expanded: { [key in string]?: boolean }, 
/**
 * Context bar position
 */
context_bar_position: string | null, 
/**
 * Pane sizes
 */
pane_sizes: { [key in string]?: JsonValue }, 
/**
 * Collapsed paths per workspace in file tree
 */
collapsed_paths: { [key in string]?: Array<string> }, 
/**
 * Preferred file-search repo
 */
file_search_repo_id: string | null, 
/**
 * Global left sidebar visibility
 */
is_left_sidebar_visible: boolean | null, 
/**
 * Global right sidebar visibility
 */
is_right_sidebar_visible: boolean | null, 
/**
 * Global terminal visibility
 */
is_terminal_visible: boolean | null, 
/**
 * Workspace-specific panel states
 */
workspace_panel_states: { [key in string]?: WorkspacePanelStateData }, 
/**
 * Workspace sidebar filter preferences
 */
workspace_filters: WorkspaceFilterStateData, 
/**
 * Workspace sidebar sort preferences
 */
workspace_sort: WorkspaceSortStateData, 
/**
 * Last selected project ID
 */
selected_project_id: string | null, 
/**
 * Default setting for creating a draft workspace from new issues
 */
create_draft_workspace_by_default: boolean | null, 
/**
 * Kanban project view selections (active view per project)
 */
kanban_project_view_selections: { [key in string]?: JsonValue }, 
/**
 * Kanban project view preferences (filters, toggles per project per view)
 */
kanban_project_view_preferences: { [key in string]?: JsonValue }, };

export type ProjectRepoDefaultsData = { repos: Array<DraftWorkspaceRepo>, };

export type ScratchPayload = { "type": "DRAFT_TASK", "data": string } | { "type": "DRAFT_FOLLOW_UP", "data": DraftFollowUpData } | { "type": "DRAFT_WORKSPACE", "data": DraftWorkspaceData } | { "type": "DRAFT_ISSUE", "data": DraftIssueData } | { "type": "PREVIEW_SETTINGS", "data": PreviewSettingsData } | { "type": "WORKSPACE_NOTES", "data": WorkspaceNotesData } | { "type": "UI_PREFERENCES", "data": UiPreferencesData } | { "type": "PROJECT_REPO_DEFAULTS", "data": ProjectRepoDefaultsData };

export enum ScratchType { DRAFT_TASK = "DRAFT_TASK", DRAFT_FOLLOW_UP = "DRAFT_FOLLOW_UP", DRAFT_WORKSPACE = "DRAFT_WORKSPACE", DRAFT_ISSUE = "DRAFT_ISSUE", PREVIEW_SETTINGS = "PREVIEW_SETTINGS", WORKSPACE_NOTES = "WORKSPACE_NOTES", UI_PREFERENCES = "UI_PREFERENCES", PROJECT_REPO_DEFAULTS = "PROJECT_REPO_DEFAULTS" }

export type Scratch = { id: string, payload: ScratchPayload, created_at: string, updated_at: string, };

export type CreateScratch = { payload: ScratchPayload, };

export type UpdateScratch = { payload: ScratchPayload, };

export type Workspace = { id: string, task_id: string | null, container_ref: string | null, branch: string, setup_completed_at: string | null, created_at: string, updated_at: string, archived: boolean, pinned: boolean, name: string | null, worktree_deleted: boolean, 
/**
 * Throwaway workspace (e.g. spec-intake generation). Excluded from list/
 * kanban queries and event streams; skips normal finalize side effects;
 * reaped on startup.
 */
ephemeral: boolean, 
/**
 * Discriminator for special-purpose workspaces. `None` = normal workspace.
 */
kind: WorkspaceKind | null, 
/**
 * Which numbered `## Pipeline` stage the execution agent last reported
 * itself as starting (1-based), detected from a `VK-PIPELINE-STAGE: N`
 * marker in the execution's raw log stream. `None` when no coding-agent
 * execution has reported a stage yet for the current run.
 */
current_pipeline_stage: bigint | null, };

export type WorkspaceKind = "orchestrator" | "recurrent";

export type WorkspaceWithStatus = { is_running: boolean, is_errored: boolean, id: string, task_id: string | null, container_ref: string | null, branch: string, setup_completed_at: string | null, created_at: string, updated_at: string, archived: boolean, pinned: boolean, name: string | null, worktree_deleted: boolean, 
/**
 * Throwaway workspace (e.g. spec-intake generation). Excluded from list/
 * kanban queries and event streams; skips normal finalize side effects;
 * reaped on startup.
 */
ephemeral: boolean, 
/**
 * Discriminator for special-purpose workspaces. `None` = normal workspace.
 */
kind: WorkspaceKind | null, 
/**
 * Which numbered `## Pipeline` stage the execution agent last reported
 * itself as starting (1-based), detected from a `VK-PIPELINE-STAGE: N`
 * marker in the execution's raw log stream. `None` when no coding-agent
 * execution has reported a stage yet for the current run.
 */
current_pipeline_stage: bigint | null, };

export type Session = { id: string, workspace_id: string, name: string | null, executor: string | null, agent_working_dir: string | null, created_at: string, updated_at: string, };

export type ExecutionProcess = { id: string, session_id: string, run_reason: ExecutionProcessRunReason, executor_action: ExecutorAction, status: ExecutionProcessStatus, exit_code: bigint | null, 
/**
 * dropped: true if this process is excluded from the current
 * history view (due to restore/trimming). Hidden from logs/timeline;
 * still listed in the Processes tab.
 */
dropped: boolean, started_at: string, completed_at: string | null, created_at: string, updated_at: string, };

export enum ExecutionProcessStatus { running = "running", completed = "completed", failed = "failed", killed = "killed" }

export type ExecutionProcessRunReason = "setupscript" | "cleanupscript" | "archivescript" | "codingagent" | "devserver";

export type ExecutionProcessRepoState = { id: string, execution_process_id: string, repo_id: string, before_head_commit: string | null, after_head_commit: string | null, merge_commit: string | null, created_at: Date, updated_at: Date, };

export type Merge = { "type": "direct" } & DirectMerge | { "type": "pr" } & PrMerge;

export type DirectMerge = { id: string, workspace_id: string, repo_id: string, merge_commit: string, target_branch_name: string, created_at: string, };

export type PrMerge = { id: string, workspace_id: string, repo_id: string, created_at: string, target_branch_name: string, pr_info: PullRequestInfo, };

export type MergeStatus = "open" | "merged" | "closed" | "unknown";

export type PullRequestInfo = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, };

export type ApprovalInfo = { approval_id: string, tool_name: string, execution_process_id: string, is_question: boolean, kind: ApprovalKind, tool_use_id?: string, 
/**
 * Present for [`ApprovalKind::Question`].
 */
questions?: Array<ApprovalQuestion>, 
/**
 * Present for [`ApprovalKind::PlanApproval`] (the plan markdown).
 */
plan_content?: string, created_at: string, timeout_at: string, };

export type ApprovalStatus = { "status": "pending" } | { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "timed_out" };

export type ApprovalKind = "tool" | "question" | "plan_approval";

export type ApprovalQuestion = { question: string, header?: string, options: Array<ApprovalQuestionOption>, multiSelect: boolean, };

export type ApprovalQuestionOption = { label: string, description?: string, };

export type QuestionAnswer = { question: string, answer: Array<string>, };

export type QuestionStatus = { "status": "answered", answers: Array<QuestionAnswer>, } | { "status": "timed_out" };

export type ApprovalOutcome = { "status": "approved" } | { "status": "denied", reason?: string, } | { "status": "answered", answers: Array<QuestionAnswer>, } | { "status": "timed_out" };

export type ApprovalResponse = { execution_process_id: string, status: ApprovalOutcome, };

export type Diff = { change: DiffChangeKind, oldPath: string | null, newPath: string | null, oldContent: string | null, newContent: string | null, 
/**
 * True when file contents are intentionally omitted (e.g., too large)
 */
contentOmitted: boolean, 
/**
 * Optional precomputed stats for omitted content
 */
additions: number | null, deletions: number | null, repoId: string | null, };

export type DiffChangeKind = "added" | "deleted" | "modified" | "renamed" | "copied" | "permissionChange";

export type ApiResponse<T, E = T> = { success: boolean, data: T | null, error_data: E | null, message: string | null, };

export type RegisterRepoRequest = { path: string, display_name: string | null, };

export type InitRepoRequest = { parent_path: string, folder_name: string, };

export type TagSearchParams = { search: string | null, };

export type TelegramStatus = { 
/**
 * `enabled = true` in telegram.toml.
 */
enabled: boolean, 
/**
 * A chat id and a resolvable bot token are both present.
 */
configured: boolean, 
/**
 * Chat id with all but the last 4 chars masked (never the full id in logs).
 */
chat_id_masked: string | null, general_thread_id: string | null, per_worktree_topics: boolean, 
/**
 * Where the bot token was resolved from, or `None` if unresolved.
 */
token_source: string | null, 
/**
 * The bridge heartbeat is present and recent.
 */
bridge_connected: boolean, bridge_last_seen: string | null, 
/**
 * Absolute path of the hand-edited config file (shown in the UI help).
 */
config_path: string, };

export type TelegramTestResponse = { ok: boolean, error: string | null, };

export type UserSystemInfo = { version: string, config: Config, environment: Environment, 
/**
 * Capabilities supported per executor (e.g., { "CLAUDE_CODE": ["SESSION_FORK"] })
 */
capabilities: { [key in string]?: Array<BaseAgentCapability> }, preview_proxy_port: number | null, executors: { [key in BaseCodingAgent]?: ExecutorProfile }, };

export type Environment = { os_type: string, os_version: string, os_architecture: string, bitness: string, };

export type McpServerQuery = { executor: BaseCodingAgent, };

export type UpdateMcpServersBody = { servers: { [key in string]?: JsonValue }, };

export type GetMcpServerResponse = { mcp_config: McpConfig, config_path: string, };

export type CheckEditorAvailabilityQuery = { editor_type: EditorType, };

export type CheckEditorAvailabilityResponse = { available: boolean, };

export type CheckAgentAvailabilityQuery = { executor: BaseCodingAgent, };

export type AgentPresetOptionsQuery = { executor: BaseCodingAgent, variant: string | null, };

export type CreateFollowUpAttempt = { prompt: string, executor_config: ExecutorConfig, retry_process_id: string | null, force_when_dirty: boolean | null, perform_git_reset: boolean | null, };

export type ResetProcessRequest = { process_id: string, force_when_dirty: boolean | null, perform_git_reset: boolean | null, };

export type ChangeTargetBranchRequest = { repo_id: string, new_target_branch: string, };

export type ChangeTargetBranchResponse = { repo_id: string, new_target_branch: string, status: [number, number], };

export type AddWorkspaceRepoRequest = { repo_id: string, target_branch: string, };

export type AddWorkspaceRepoResponse = { workspace: Workspace, repo: RepoWithTargetBranch, };

export type MergeWorkspaceRequest = { repo_id: string, };

export type CommitWorkspaceRequest = { repo_id: string, };

export type CommitWorkspaceResponse = { 
/**
 * Whether a new commit was created. `false` means the worktree was clean
 * (nothing to commit) — not an error.
 */
committed: boolean, };

export type PushWorkspaceRequest = { repo_id: string, };

export type RenameBranchRequest = { new_branch_name: string, };

export type RenameBranchResponse = { branch: string, };

export type StartReviewRequest = { executor_config: ExecutorConfig, additional_prompt: string | null, use_all_workspace_commits: boolean, };

export type ReviewError = { "type": "process_already_running" };

export type OpenEditorRequest = { editor_type: string | null, file_path: string | null, };

export type OpenEditorResponse = { url: string | null, };

export type CreateWorkspaceApiRequest = { name: string | null, };

export type LinkedIssueInfo = { remote_project_id: string, issue_id: string, };

export type CreatePrApiRequest = { title: string, body: string | null, target_branch: string | null, draft: boolean | null, repo_id: string, auto_generate_description: boolean, };

export type AttachmentResponse = { id: string, file_path: string, original_name: string, mime_type: string | null, size_bytes: bigint, hash: string, created_at: string, updated_at: string, };

export type AttachmentMetadata = { exists: boolean, file_name: string | null, path: string | null, size_bytes: bigint | null, format: string | null, proxy_url: string | null, };

export type WorkspaceRepoInput = { repo_id: string, target_branch: string, };

export type RunAgentSetupRequest = { executor_profile_id: ExecutorProfileId, };

export type RunAgentSetupResponse = Record<string, never>;

export type GhCliSetupError = "BREW_MISSING" | "SETUP_HELPER_NOT_SUPPORTED" | { "OTHER": { message: string, } };

export type RebaseWorkspaceRequest = { repo_id: string, old_base_branch: string | null, new_base_branch: string | null, };

export type ContinueRebaseRequest = { repo_id: string, };

export type AbortConflictsRequest = { repo_id: string, };

export type GitOperationError = { "type": "merge_conflicts", message: string, op: ConflictOp, conflicted_files: Array<string>, target_branch: string, } | { "type": "rebase_in_progress" };

export type PushError = { "type": "force_push_required" };

export type PrError = { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "cli_not_logged_in", provider: ProviderKind, } | { "type": "git_cli_not_logged_in" } | { "type": "git_cli_not_installed" } | { "type": "target_branch_not_found", branch: string, } | { "type": "unsupported_provider" };

export type RunScriptError = { "type": "no_script_configured" } | { "type": "process_already_running" };

export type AssociateWorkspaceAttachmentsRequest = { attachment_ids: Array<string>, };

export type AttachPrResponse = { pr_attached: boolean, pr_url: string | null, pr_number: bigint | null, pr_status: MergeStatus | null, };

export type AttachExistingPrRequest = { repo_id: string, };

export type PrCommentsResponse = { comments: Array<UnifiedPrComment>, };

export type GetPrCommentsError = { "type": "no_pr_attached" } | { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "cli_not_logged_in", provider: ProviderKind, };

export type GetPrCommentsQuery = { repo_id: string, };

export type CreateAndStartWorkspaceRequest = { name: string | null, repos: Array<WorkspaceRepoInput>, linked_issue: LinkedIssueInfo | null, executor_config: ExecutorConfig, prompt: string, attachment_ids: Array<string> | null, 
/**
 * Discriminator for special-purpose workspaces (e.g. `orchestrator`).
 * Omitted by older clients and the MCP crate; defaults to a normal
 * workspace.
 */
kind?: WorkspaceKind, };

export type CreateAndStartWorkspaceResponse = { workspace: Workspace, execution_process: ExecutionProcess, };

export type SpawnOrchestratorRequest = { 
/**
 * The `/loop`-wrapped orchestration brief composed from the enabled
 * directives.
 */
prompt: string, 
/**
 * Display name for the orchestrator workspace; defaults to "Orchestrator".
 */
name?: string, 
/**
 * The headed executor backend for the orchestrator session. Defaults to
 * Claude Code Headed when omitted or non-headed. OpenCode Headed is the
 * alternative backend (useful when Claude Code is unavailable).
 */
executor?: BaseCodingAgent, };

export type SpawnOrchestratorResponse = { workspace: Workspace, 
/**
 * True when an already-running orchestrator was returned instead of
 * starting a new session (its live tmux session is reused).
 */
reused: boolean, };

export type CloseOrchestratorResponse = { 
/**
 * True when a running orchestrator session was stopped; false when there
 * was no orchestrator (or no live session) to close.
 */
closed: boolean, };

export type GenerateSpecRequest = { 
/**
 * Project the card will belong to. Provenance/context only — the local
 * backend does not validate remote repo membership against it.
 */
project_id: string, 
/**
 * The rough, minimal task brief from the user.
 */
brief: string, 
/**
 * Selected agent parameters (executor/variant/model), same shape as
 * the create-workspace flow.
 */
executor_config: ExecutorConfig, 
/**
 * Repos (with target branch) to mount in the ephemeral workspace so the
 * agent can explore the codebase.
 */
repos: Array<WorkspaceRepoInput>, };

export type GenerateSpecResponse = { title: string, description: string, 
/**
 * `{ "intake": { brief, executor_config, repos } }` — drop verbatim into
 * `CreateIssueRequest.extension_metadata`.
 */
intake_metadata: JsonValue, };

export type SpecKitStage = "constitution" | "specify" | "clarify" | "plan" | "tasks" | "analyze" | "implement";

export type SpecKitStageState = "idle" | "running" | "done" | "needs_attention";

export type SpecKitTask = { 
/**
 * Task identifier as written in tasks.md (e.g. "T001"). Falls back to the
 * 1-based ordinal when the source line has no explicit id.
 */
id: string, 
/**
 * Human-readable task description (the text after the id/marker).
 */
description: string, 
/**
 * File paths referenced in the task line, when present.
 */
file_paths: Array<string>, 
/**
 * True when the task is marked `[P]` (safe to run in parallel).
 */
parallelizable: boolean, 
/**
 * Phase / user-story heading the task is grouped under, if any.
 */
phase?: string, 
/**
 * Whether the task's checkbox is ticked (`[x]`).
 */
done: boolean, };

export type SpecKitTaskLayer = { 
/**
 * Task ids that make up this layer.
 */
task_ids: Array<string>, 
/**
 * True when the layer holds more than one task (i.e. real parallelism).
 */
parallel: boolean, };

export type SpecKitTasks = { tasks: Array<SpecKitTask>, 
/**
 * Ordered parallel layers derived from `[P]` markers + task order.
 */
layers: Array<SpecKitTaskLayer>, total: number, completed: number, };

export type SpecKitArtifact = { 
/**
 * Display name / filename (e.g. "spec.md").
 */
name: string, 
/**
 * Path relative to the feature dir (e.g. "contracts/api-spec.json").
 */
relative_path: string, content?: string, exists: boolean, };

export type SpecKitArtifacts = { 
/**
 * Feature dir relative to the repo root, e.g. "specs/001-webhook-retries".
 */
feature_dir: string, spec: SpecKitArtifact, plan: SpecKitArtifact, tasks: SpecKitArtifact, research: SpecKitArtifact, data_model: SpecKitArtifact, quickstart: SpecKitArtifact, 
/**
 * Contract files under `contracts/` (json / markdown), if any.
 */
contracts: Array<SpecKitArtifact>, };

export type UpdateArtifactRequest = { 
/**
 * Path relative to the feature dir (e.g. "spec.md", "contracts/api.json").
 */
relative_path: string, content: string, };

export type ToggleTaskRequest = { task_id: string, done: boolean, };

export type ConstitutionContent = { content: string, exists: boolean, };

export type SpecKitFeatureStatus = { issue_id: string, enabled: boolean, 
/**
 * Explains why `enabled` is false (no linked workspace vs. multi-repo),
 * so the frontend can show accurate copy without re-deriving it.
 */
note?: string, workspace_id?: string, feature_slug?: string, feature_dir?: string, };

export type AnalyzeFinding = { 
/**
 * "error" | "warning" | "info".
 */
severity: string, message: string, 
/**
 * The artifact the finding points at, when known (e.g. "spec.md").
 */
artifact?: string, };

export type UpdateOrchestratorPromptRequest = { orchestrator_prompt: string, };

export type OrchestratorPromptResponse = { project_id: string, orchestrator_prompt: string, };

export type ResolvedOrchestratorPromptResponse = { project_id: string, orchestrator_prompt: string, source_project_id: string | null, source: OrchestratorPromptSource, };

export type OrchestratorPromptSource = "self" | "ancestor" | "default";

export type UnifiedPrComment = { "comment_type": "general", id: string, author: string, author_association: string | null, body: string, created_at: string, url: string | null, } | { "comment_type": "review", id: bigint, author: string, author_association: string | null, body: string, created_at: string, url: string | null, path: string, line: bigint | null, side: string | null, diff_hunk: string | null, };

export type ProviderKind = "git_hub" | "unknown";

export type PullRequestDetail = { number: bigint, url: string, status: MergeStatus, merged_at: string | null, merge_commit_sha: string | null, title: string, base_branch: string, head_branch: string, };

export type GitRemote = { name: string, url: string, };

export type ListPrsError = { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "auth_failed", message: string, } | { "type": "unsupported_provider" };

export type CreateWorkspaceFromPrBody = { repo_id: string, pr_number: bigint, pr_title: string, pr_url: string, head_branch: string, base_branch: string, run_setup: boolean, remote_name: string | null, };

export type CreateWorkspaceFromPrResponse = { workspace: Workspace, };

export type CreateFromPrError = { "type": "pr_not_found" } | { "type": "branch_fetch_failed", message: string, } | { "type": "cli_not_installed", provider: ProviderKind, } | { "type": "auth_failed", message: string, } | { "type": "unsupported_provider" };

export type RepoBranchStatus = { repo_id: string, repo_name: string, commits_behind: number | null, commits_ahead: number | null, has_uncommitted_changes: boolean | null, head_oid: string | null, uncommitted_count: number | null, untracked_count: number | null, target_branch_name: string, remote_commits_behind: number | null, remote_commits_ahead: number | null, merges: Array<Merge>, is_rebase_in_progress: boolean, conflict_op: ConflictOp | null, conflicted_files: Array<string>, is_target_remote: boolean, };

export type UpdateWorkspace = { archived: boolean | null, pinned: boolean | null, name: string | null, };

export type UpdateSession = { name: string | null, };

export type WorkspaceSummaryRequest = { archived: boolean, };

export type WorkspaceSummary = { workspace_id: string, 
/**
 * Session ID of the latest execution process
 */
latest_session_id: string | null, 
/**
 * Is a tool approval currently pending?
 */
has_pending_approval: boolean, 
/**
 * Number of files with changes
 */
files_changed: number | null, 
/**
 * Total lines added across all files
 */
lines_added: number | null, 
/**
 * Total lines removed across all files
 */
lines_removed: number | null, 
/**
 * When the latest execution process completed
 */
latest_process_completed_at?: string, 
/**
 * Status of the latest execution process
 */
latest_process_status: ExecutionProcessStatus | null, 
/**
 * Is a dev server currently running?
 */
has_running_dev_server: boolean, 
/**
 * Does this workspace have unseen coding agent turns?
 */
has_unseen_turns: boolean, 
/**
 * PR status for this workspace (if any PR exists)
 */
pr_status: MergeStatus | null, 
/**
 * PR number for this workspace (if any PR exists)
 */
pr_number: bigint | null, 
/**
 * PR URL for this workspace (if any PR exists)
 */
pr_url: string | null, };

export type WorkspaceSummaryResponse = { summaries: Array<WorkspaceSummary>, };

export type DiffStats = { files_changed: number, lines_added: number, lines_removed: number, };

export type DirectoryEntry = { name: string, path: string, is_directory: boolean, is_git_repo: boolean, last_modified: bigint | null, };

export type DirectoryListResponse = { entries: Array<DirectoryEntry>, current_path: string, };

export type SearchMode = "taskform" | "settings";

export type Config = { config_version: string, theme: ThemeMode, executor_profile: ExecutorProfileId, disclaimer_acknowledged: boolean, onboarding_acknowledged: boolean, remote_onboarding_acknowledged: boolean, notifications: NotificationConfig, editor: EditorConfig, github: GitHubConfig, workspace_dir: string | null, last_app_version: string | null, show_release_notes: boolean, language: UiLanguage, git_branch_prefix: string, showcases: ShowcaseState, pr_auto_description_enabled: boolean, pr_auto_description_prompt: string | null, commit_reminder_enabled: boolean, commit_reminder_prompt: string | null, send_message_shortcut: SendMessageShortcut, host_nickname: string | null, 
/**
 * Terminal emulator used to attach to interactive agent sessions.
 */
terminal: TerminalKind, 
/**
 * When the terminal is iTerm2, group sessions as tabs of one window
 * instead of opening a new window per session.
 */
iterm_tabs: boolean, 
/**
 * User-configured extra origins allowed by the origin-check middleware
 * (in addition to loopback + same-origin). Each entry is a full URL
 * like `http://192.168.1.50:3001`. Editable via Settings UI.
 */
allowed_origins: Array<string>, 
/**
 * Deprecated and ignored. Pipelines are now file-based
 * (`~/.vibe-kanban/pipelines/*.toml`, see `services::services::pipelines`);
 * this field is retained only so pre-existing configs still deserialise. It
 * is no longer read or written by the UI.
 */
pipeline_steps: Array<PipelineStep> | null, };

export type PipelineStep = { 
/**
 * Stable slug, e.g. "spec".
 */
id: string, 
/**
 * Shown next to the New Issue checkbox.
 */
label: string, 
/**
 * Appended as a bullet when the step is ticked.
 */
prompt_fragment: string, 
/**
 * Whether the card checkbox starts ticked.
 */
default_enabled: boolean, 
/**
 * Whether this stage is marked "heavy" (resource-intensive); the UI
 * renders a badge and it starts unticked by convention.
 */
heavy: boolean, };

export type Pipeline = { 
/**
 * Stable slug = the file stem, e.g. "basic".
 */
id: string, 
/**
 * Display name from the file's `name` field.
 */
name: string, 
/**
 * Optional one-line description.
 */
description: string | null, 
/**
 * Ordered stages; this order is authoritative for the composed block.
 */
stages: Array<PipelineStep>, };

export type PipelineParseError = { message: string, line: number | null, column: number | null, };

export type PipelineValidation = { valid: boolean, error: PipelineParseError | null, };

export type PipelineFileStatus = { id: string, name: string, stage_count: number | null, valid: boolean, error: PipelineParseError | null, };

export type PipelineRawBody = { content: string, };

export type PipelineValidateBody = { id: string | null, content: string, };

export type Routine = { 
/**
 * Stable slug = the file stem, e.g. "inbox-triage".
 */
id: string, name: string, enabled: boolean, prompt: string, 
/**
 * Optional `--agent` id (e.g. "vibe-kanban-indie:orchestrator").
 */
agent: string | null, 
/**
 * Resolved `BaseCodingAgent` SCREAMING_SNAKE_CASE string, e.g. "CLAUDE_CODE".
 */
executor_profile: string, max_runtime_secs: bigint, schedule: RoutineScheduleView, last_run: RoutineLastRun | null, };

export type RoutineLastRun = { status: string, at: string, 
/**
 * Workspace the run executed in, so the UI can jump straight to it.
 */
workspace_id: string, };

export type RoutineScheduleView = { 
/**
 * `"cron"` or `"interval"`.
 */
kind: string, 
/**
 * The raw expression (`"0 9 * * *"` or `"30m"`).
 */
expr: string, };

export type RecurrentRawBody = { content: string, };

export type RecurrentTomlError = { message: string, };

export type RunRoutineResponse = { 
/**
 * `false` when a previous run was still active and nothing new was
 * spawned (`SpawnOutcome::SkippedActive`).
 */
spawned: boolean, workspace_id: string | null, };

export type NotificationConfig = { sound_enabled: boolean, push_enabled: boolean, sound_file: SoundFile, };

export enum ThemeMode { LIGHT = "LIGHT", DARK = "DARK", SYSTEM = "SYSTEM" }

export type EditorConfig = { editor_type: EditorType, custom_command: string | null, remote_ssh_host: string | null, remote_ssh_user: string | null, auto_install_extension: boolean, };

export enum EditorType { VS_CODE = "VS_CODE", VS_CODE_INSIDERS = "VS_CODE_INSIDERS", CURSOR = "CURSOR", WINDSURF = "WINDSURF", INTELLI_J = "INTELLI_J", ZED = "ZED", XCODE = "XCODE", GOOGLE_ANTIGRAVITY = "GOOGLE_ANTIGRAVITY", CUSTOM = "CUSTOM" }

export type EditorOpenError = { "type": "executable_not_found", executable: string, editor_type: EditorType, } | { "type": "invalid_command", details: string, editor_type: EditorType, } | { "type": "launch_failed", executable: string, details: string, editor_type: EditorType, };

export type GitHubConfig = { pat: string | null, oauth_token: string | null, username: string | null, primary_email: string | null, default_pr_base: string | null, };

export enum SoundFile { ABSTRACT_SOUND1 = "ABSTRACT_SOUND1", ABSTRACT_SOUND2 = "ABSTRACT_SOUND2", ABSTRACT_SOUND3 = "ABSTRACT_SOUND3", ABSTRACT_SOUND4 = "ABSTRACT_SOUND4", COW_MOOING = "COW_MOOING", FAHHHHH = "FAHHHHH", PHONE_VIBRATION = "PHONE_VIBRATION", ROOSTER = "ROOSTER" }

export type UiLanguage = "BROWSER" | "EN" | "FR" | "JA" | "ES" | "KO" | "ZH_HANS" | "ZH_HANT";

export type ShowcaseState = { seen_features: Array<string>, };

export type SendMessageShortcut = "ModifierEnter" | "Enter";

export type GitBranch = { name: string, is_current: boolean, is_remote: boolean, last_commit_date: Date, };

export type QueuedMessage = { 
/**
 * The session this message is queued for
 */
session_id: string, 
/**
 * The follow-up data (message + variant)
 */
data: DraftFollowUpData, 
/**
 * Timestamp when the message was queued
 */
queued_at: string, };

export type QueueStatus = { "status": "empty" } | { "status": "queued", message: QueuedMessage, };

export type ConflictOp = "rebase" | "merge" | "cherry_pick" | "revert";

export type ExecutorAction = { typ: ExecutorActionType, next_action: ExecutorAction | null, };

export type McpConfig = { servers: { [key in string]?: JsonValue }, servers_path: Array<string>, template: JsonValue, preconfigured: JsonValue, is_toml_config: boolean, };

export type ExecutorActionType = { "type": "CodingAgentInitialRequest" } & CodingAgentInitialRequest | { "type": "CodingAgentFollowUpRequest" } & CodingAgentFollowUpRequest | { "type": "ScriptRequest" } & ScriptRequest | { "type": "ReviewRequest" } & ReviewRequest;

export type ExecutorConfig = { 
/**
 * The executor type (e.g., CLAUDE_CODE, AMP)
 */
executor: BaseCodingAgent, 
/**
 * Optional variant/preset name (e.g., "PLAN", "ROUTER")
 */
variant?: string | null, 
/**
 * Model override (e.g., "anthropic/claude-sonnet-4-20250514")
 */
model_id?: string | null, 
/**
 * Agent mode override
 */
agent_id?: string | null, 
/**
 * Reasoning effort override (e.g., "high", "medium")
 */
reasoning_id?: string | null, 
/**
 * Permission policy override
 */
permission_policy?: PermissionPolicy | null, };

export type ScriptContext = "SetupScript" | "CleanupScript" | "ArchiveScript" | "DevServer" | "ToolInstallScript";

export type ScriptRequest = { script: string, language: ScriptRequestLanguage, context: ScriptContext, 
/**
 * Optional relative path to execute the script in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, };

export type ScriptRequestLanguage = "Bash";

export enum BaseCodingAgent { CLAUDE_CODE = "CLAUDE_CODE", CLAUDE_CODE_HEADED = "CLAUDE_CODE_HEADED", AMP = "AMP", GEMINI = "GEMINI", CODEX = "CODEX", OPENCODE = "OPENCODE", OPENCODE_HEADED = "OPENCODE_HEADED", CURSOR_AGENT = "CURSOR_AGENT", QWEN_CODE = "QWEN_CODE", COPILOT = "COPILOT", DROID = "DROID" }

export type CodingAgent = { "CLAUDE_CODE": ClaudeCode } | { "CLAUDE_CODE_HEADED": ClaudeCodeHeaded } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "OPENCODE_HEADED": OpencodeHeaded } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid };

export type SlashCommandDescription = { 
/**
 * Command name without the leading slash, e.g. `help` for `/help`.
 */
name: string, description?: string | null, };

export type AvailabilityInfo = { "type": "LOGIN_DETECTED", last_auth_timestamp: bigint, } | { "type": "INSTALLATION_FOUND" } | { "type": "NOT_FOUND" };

export type CommandBuilder = { 
/**
 * Base executable command (e.g., "npx -y @anthropic-ai/claude-code@latest")
 */
base: string, 
/**
 * Optional parameters to append to the base command
 */
params: Array<string> | null, };

export type ExecutorProfileId = { 
/**
 * The executor type (e.g., "CLAUDE_CODE", "AMP")
 */
executor: BaseCodingAgent, 
/**
 * Optional variant name (e.g., "PLAN", "ROUTER")
 */
variant: string | null, };

export type ExecutorRecentModels = { 
/**
 * Ordered list of recently used model keys (most recent last).
 */
models?: Array<string>, 
/**
 * Last-used reasoning effort per model
 */
reasoning_by_model?: { [key in string]?: string }, };

export type ExecutorProfile = { recently_used_models?: ExecutorRecentModels | null, } & ({ [key in string]?: { "CLAUDE_CODE": ClaudeCode } | { "CLAUDE_CODE_HEADED": ClaudeCodeHeaded } | { "AMP": Amp } | { "GEMINI": Gemini } | { "CODEX": Codex } | { "OPENCODE": Opencode } | { "OPENCODE_HEADED": OpencodeHeaded } | { "CURSOR_AGENT": CursorAgent } | { "QWEN_CODE": QwenCode } | { "COPILOT": Copilot } | { "DROID": Droid } });

export type ExecutorConfigs = { executors: { [key in BaseCodingAgent]?: ExecutorProfile }, };

export enum BaseAgentCapability { SESSION_FORK = "SESSION_FORK", SETUP_HELPER = "SETUP_HELPER", CONTEXT_USAGE = "CONTEXT_USAGE" }

export type ClaudeEffort = "low" | "medium" | "high" | "xhigh" | "max";

export type ClaudeCode = { append_prompt: AppendPrompt, claude_code_router?: boolean | null, plan?: boolean | null, approvals?: boolean | null, model?: string | null, effort?: ClaudeEffort | null, agent?: string | null, dangerously_skip_permissions?: boolean | null, disable_api_key?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type ClaudeCodeHeaded = { 
/**
 * Load the Sombrax Telegram channel into the headed session. When enabled,
 * vibe-kanban appends [`TELEGRAM_CHANNEL_FLAG`] to the interactive command
 * and auto-confirms the startup prompts (folder-trust + the dev-channel
 * warning) by pressing Enter in the tmux session.
 */
telegram_channel?: boolean | null, 
/**
 * Spawn the locally-installed `claude` binary (resolved on `PATH`) instead
 * of the pinned npx package used by the headless path. Defaults to **on**:
 * the headed TUI is interactive, so the operator's own — normally more
 * up-to-date — install is preferable to a version frozen at build time.
 * An explicit `base_command_override` or `claude_code_router` take
 * precedence (see the container's interactive launch path). Disable to fall
 * back to the pinned npx package.
 */
local_binary?: boolean | null, 
/**
 * Open a terminal-emulator window attached to the session when a headed run
 * starts. When disabled, the agent still runs in a detached tmux session
 * (attach later with `tmux attach -t vk-<id>`) but no window is opened.
 *
 * A non-`Option` `bool` with a serde default of `true` on purpose: schemars
 * emits that default into the generated schema (`"default": true`), which is
 * what makes the RJSF checkbox render *checked* by default. An `Option<bool>`
 * would leave the box unchecked-but-on (the `local_binary` wart above).
 */
open_terminal: boolean, append_prompt: AppendPrompt, claude_code_router?: boolean | null, plan?: boolean | null, approvals?: boolean | null, model?: string | null, effort?: ClaudeEffort | null, agent?: string | null, dangerously_skip_permissions?: boolean | null, disable_api_key?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Gemini = { append_prompt: AppendPrompt, model?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Amp = { append_prompt: AppendPrompt, dangerously_allow_all?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Codex = { append_prompt: AppendPrompt, sandbox?: SandboxMode | null, ask_for_approval?: AskForApproval | null, oss?: boolean | null, model?: string | null, model_reasoning_effort?: ReasoningEffort | null, model_reasoning_summary?: ReasoningSummary | null, model_reasoning_summary_format?: ReasoningSummaryFormat | null, profile?: string | null, base_instructions?: string | null, include_apply_patch_tool?: boolean | null, model_provider?: string | null, compact_prompt?: string | null, developer_instructions?: string | null, plan: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type SandboxMode = "auto" | "read-only" | "workspace-write" | "danger-full-access";

export type AskForApproval = "unless-trusted" | "on-failure" | "on-request" | "never";

export type ReasoningEffort = "low" | "medium" | "high" | "xhigh";

export type ReasoningSummary = "auto" | "concise" | "detailed" | "none";

export type ReasoningSummaryFormat = "none" | "experimental";

export type CursorAgent = { append_prompt: AppendPrompt, force?: boolean | null, model?: string | null, reasoning?: string | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Copilot = { append_prompt: AppendPrompt, model?: string | null, allow_all_tools?: boolean | null, allow_tool?: string | null, deny_tool?: string | null, add_dir?: Array<string> | null, disable_mcp_server?: Array<string> | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Opencode = { append_prompt: AppendPrompt, model?: string | null, variant?: string | null, agent?: string | null, 
/**
 * Auto-approve agent actions
 */
auto_approve: boolean, 
/**
 * Enable auto-compaction when the context length approaches the model's context window limit
 */
auto_compact: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type OpencodeHeaded = { 
/**
 * Load the Sombrax Telegram channel into the headed session (parity with
 * [`ClaudeCodeHeaded::telegram_channel`]). Currently advisory for opencode.
 */
telegram_channel?: boolean | null, 
/**
 * Open a terminal-emulator window attached to the session when a headed run
 * starts. When disabled, the agent still runs in a detached tmux session
 * (`tmux attach -t vk-<id>`) but no window is opened. A non-`Option` `bool`
 * with a serde default of `true` so the RJSF checkbox renders checked.
 */
open_terminal: boolean, append_prompt: AppendPrompt, model?: string | null, variant?: string | null, agent?: string | null, 
/**
 * Auto-approve agent actions
 */
auto_approve: boolean, 
/**
 * Enable auto-compaction when the context length approaches the model's context window limit
 */
auto_compact: boolean, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type QwenCode = { append_prompt: AppendPrompt, model?: string | null, agent?: string | null, yolo?: boolean | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Droid = { append_prompt: AppendPrompt, autonomy: Autonomy, model?: string | null, reasoning_effort?: DroidReasoningEffort | null, base_command_override?: string | null, additional_params?: Array<string> | null, env?: { [key in string]?: string } | null, };

export type Autonomy = "normal" | "low" | "medium" | "high" | "skip-permissions-unsafe";

export type DroidReasoningEffort = "none" | "dynamic" | "off" | "low" | "medium" | "high";

export type AppendPrompt = string | null;

export type TerminalKind = "I_TERM2" | "WEZ_TERM" | "TERMINAL_APP" | "GNOME_TERMINAL" | "XTERM" | "NONE";

export type InteractiveTmuxConfig = { 
/**
 * Forced Claude session id (`claude --session-id <uuid>` / `--resume
 * <uuid>`). Generated when the action is built so the caller can display
 * it and so resume reattaches to the same conversation.
 */
session_uuid: string, 
/**
 * Terminal emulator to attach with, frozen at launch.
 */
terminal: TerminalKind, };

export type CodingAgentInitialRequest = { prompt: string, 
/**
 * Unified executor identity + overrides
 */
executor_config: ExecutorConfig, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, 
/**
 * When set, run the agent in an interactive terminal (detached tmux
 * session) instead of the headless `-p` protocol. Backward compatible:
 * existing actions deserialize as `None` and take the headless path.
 */
interactive?: InteractiveTmuxConfig | null, };

export type CodingAgentFollowUpRequest = { prompt: string, session_id: string, reset_to_message_id: string | null, 
/**
 * Unified executor identity + overrides
 */
executor_config: ExecutorConfig, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 * If None, uses the container_ref directory directly.
 */
working_dir: string | null, 
/**
 * When set, resume the agent in an interactive terminal (detached tmux
 * session) instead of the headless `-p` protocol. Backward compatible.
 */
interactive?: InteractiveTmuxConfig | null, };

export type ReviewRequest = { 
/**
 * Unified executor identity + overrides
 */
executor_config: ExecutorConfig, context: Array<RepoReviewContext> | null, prompt: string, 
/**
 * Optional session ID to resume an existing session
 */
session_id: string | null, 
/**
 * Optional relative path to execute the agent in (relative to container_ref).
 */
working_dir: string | null, };

export type RepoReviewContext = { repo_id: string, repo_name: string, base_commit: string, };

export type CommandExitStatus = { "type": "exit_code", code: number, } | { "type": "success", success: boolean, };

export type CommandRunResult = { exit_status: CommandExitStatus | null, output: string | null, };

export type CommandCategory = "read" | "search" | "edit" | "fetch" | "other";

export type NormalizedEntry = { timestamp: string | null, entry_type: NormalizedEntryType, content: string, };

export type NormalizedEntryType = { "type": "user_message" } | { "type": "user_feedback", denied_tool: string, } | { "type": "assistant_message" } | { "type": "tool_use", tool_name: string, action_type: ActionType, status: ToolStatus, } | { "type": "system_message" } | { "type": "error_message", error_type: NormalizedEntryError, } | { "type": "thinking" } | { "type": "loading" } | { "type": "turn_complete" } | { "type": "next_action", failed: boolean, execution_processes: number, needs_setup: boolean, } | { "type": "token_usage_info" } & TokenUsageInfo | { "type": "user_answered_questions", answers: Array<AnsweredQuestion>, };

export type TokenUsageInfo = { total_tokens: number, model_context_window: number, };

export type FileChange = { "action": "write", content: string, } | { "action": "delete" } | { "action": "rename", new_path: string, } | { "action": "edit", 
/**
 * Unified diff containing file header and hunks.
 */
unified_diff: string, 
/**
 * Whether line number in the hunks are reliable.
 */
has_line_numbers: boolean, };

export type ActionType = { "action": "file_read", path: string, } | { "action": "file_edit", path: string, changes: Array<FileChange>, } | { "action": "command_run", command: string, result: CommandRunResult | null, category: CommandCategory, } | { "action": "search", query: string, } | { "action": "web_fetch", url: string, } | { "action": "tool", tool_name: string, arguments: JsonValue | null, result: ToolResult | null, } | { "action": "task_create", description: string, subagent_type: string | null, result: ToolResult | null, } | { "action": "plan_presentation", plan: string, } | { "action": "todo_management", todos: Array<TodoItem>, operation: string, } | { "action": "ask_user_question", questions: Array<AskUserQuestionItem>, } | { "action": "other", description: string, };

export type AnsweredQuestion = { question: string, answer: Array<string>, };

export type AskUserQuestionItem = { question: string, header: string, options: Array<AskUserQuestionOption>, multiSelect: boolean, };

export type AskUserQuestionOption = { label: string, description: string, };

export type TodoItem = { content: string, status: string, priority: string | null, };

export type NormalizedEntryError = { "type": "setup_required" } | { "type": "other" };

export type ToolResult = { type: ToolResultValueType, 
/**
 * For Markdown, this will be a JSON string; for JSON, a structured value
 */
value: JsonValue, };

export type ToolResultValueType = { "type": "markdown" } | { "type": "json" };

export type ToolStatus = { "status": "created" } | { "status": "success" } | { "status": "failed" } | { "status": "denied", reason: string | null, } | { "status": "pending_approval", approval_id: string, } | { "status": "timed_out" };

export type PatchType = { "type": "NORMALIZED_ENTRY", "content": NormalizedEntry } | { "type": "STDOUT", "content": string } | { "type": "STDERR", "content": string } | { "type": "DIFF", "content": Diff };

export type ModelInfo = { 
/**
 * Model identifier
 */
id: string, 
/**
 * Display name
 */
name: string, 
/**
 * Provider this model belongs to
 */
provider_id?: string | null, 
/**
 * Configurable reasoning options if supported
 */
reasoning_options: Array<ReasoningOption>, };

export type ReasoningOption = { id: string, label: string, is_default: boolean, };

export type ModelProvider = { 
/**
 * Provider identifier
 */
id: string, 
/**
 * Display name
 */
name: string, };

export type AgentInfo = { id: string, label: string, description?: string | null, is_default: boolean, };

export enum PermissionPolicy { AUTO = "AUTO", SUPERVISED = "SUPERVISED", PLAN = "PLAN" }

export type ModelSelectorConfig = { 
/**
 * Available providers
 */
providers: Array<ModelProvider>, 
/**
 * Available models
 */
models: Array<ModelInfo>, 
/**
 * Global default model (format: provider_id/model_id)
 */
default_model?: string | null, 
/**
 * Available agents
 */
agents: Array<AgentInfo>, 
/**
 * Supported permission policies
 */
permissions: Array<PermissionPolicy>, };

export type ExecutorDiscoveredOptions = { model_selector: ModelSelectorConfig, slash_commands: Array<SlashCommandDescription>, loading_models: boolean, loading_agents: boolean, loading_slash_commands: boolean, error: string | null, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]?: JsonValue } | null;

export const DEFAULT_PR_DESCRIPTION_PROMPT = "Update the PR that was just created with a better title and description.\nThe PR number is #{pr_number} and the URL is {pr_url}.\n\nAnalyze the changes in this branch and write:\n1. A concise, descriptive title that summarizes the changes, postfixed with \"(Vibe Kanban)\"\n2. A detailed description that explains:\n   - What changes were made\n   - Why they were made (based on the task context)\n   - Any important implementation details\n   - At the end, include a note: \"This PR was written using [Vibe Kanban](https://vibekanban.com)\"\n\nUpdate the PR using gh pr edit.";

export const DEFAULT_COMMIT_REMINDER_PROMPT = "There are uncommitted changes. Please stage and commit them now with a descriptive commit message.";