/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as AppCommonTasksRouteImport } from './routes/_app.common-tasks'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as WorkspacesWorkspaceIdVscodeRouteImport } from './routes/workspaces.$workspaceId.vscode'
import { Route as AppWorkspacesCreateRouteImport } from './routes/_app.workspaces_.create'
import { Route as AppWorkspacesWorkspaceIdRouteImport } from './routes/_app.workspaces_.$workspaceId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProjectsProjectIdOrchestratorPromptRouteImport } from './routes/_app.projects.$projectId_.orchestrator-prompt'
import { Route as AppHostsHostIdWorkspacesRouteImport } from './routes/_app.hosts.$hostId.workspaces'
import { Route as HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport } from './routes/hosts.$hostId.workspaces.$workspaceId.vscode'
import { Route as AppProjectsProjectIdSpeckitFeatureIdRouteImport } from './routes/_app.projects.$projectId_.speckit.$featureId'
import { Route as AppProjectsProjectIdIssuesIssueIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId'
import { Route as AppHostsHostIdWorkspacesCreateRouteImport } from './routes/_app.hosts.$hostId.workspaces_.create'
import { Route as AppHostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.hosts.$hostId.workspaces_.$workspaceId'
import { Route as AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.workspaces.$workspaceId'
import { Route as AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.hosts.$hostId.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.hosts.$hostId.workspaces.$workspaceId'
import { Route as AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.hosts.$hostId.workspaces.create.$draftId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppCommonTasksRoute = AppCommonTasksRouteImport.update({
  id: '/common-tasks',
  path: '/common-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const WorkspacesWorkspaceIdVscodeRoute =
  WorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/workspaces/$workspaceId/vscode',
    path: '/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesCreateRoute = AppWorkspacesCreateRouteImport.update({
  id: '/workspaces_/create',
  path: '/workspaces/create',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesWorkspaceIdRoute =
  AppWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces_/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdOrchestratorPromptRoute =
  AppProjectsProjectIdOrchestratorPromptRouteImport.update({
    id: '/projects/$projectId_/orchestrator-prompt',
    path: '/projects/$projectId/orchestrator-prompt',
    getParentRoute: () => AppRoute,
  } as any)
const AppHostsHostIdWorkspacesRoute =
  AppHostsHostIdWorkspacesRouteImport.update({
    id: '/hosts/$hostId/workspaces',
    path: '/hosts/$hostId/workspaces',
    getParentRoute: () => AppRoute,
  } as any)
const HostsHostIdWorkspacesWorkspaceIdVscodeRoute =
  HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    path: '/hosts/$hostId/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppProjectsProjectIdSpeckitFeatureIdRoute =
  AppProjectsProjectIdSpeckitFeatureIdRouteImport.update({
    id: '/projects/$projectId_/speckit/$featureId',
    path: '/projects/$projectId/speckit/$featureId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdRoute =
  AppProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId',
    path: '/projects/$projectId/issues/$issueId',
    getParentRoute: () => AppRoute,
  } as any)
const AppHostsHostIdWorkspacesCreateRoute =
  AppHostsHostIdWorkspacesCreateRouteImport.update({
    id: '/hosts/$hostId/workspaces_/create',
    path: '/hosts/$hostId/workspaces/create',
    getParentRoute: () => AppRoute,
  } as any)
const AppHostsHostIdWorkspacesWorkspaceIdRoute =
  AppHostsHostIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/hosts/$hostId/workspaces_/$workspaceId',
    path: '/hosts/$hostId/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/projects/$projectId_/workspaces/create/$draftId',
    path: '/projects/$projectId/workspaces/create/$draftId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute =
  AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId',
    path: '/projects/$projectId/issues/$issueId/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId',
    path: '/projects/$projectId/issues/$issueId/workspaces/create/$draftId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId',
    path: '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute =
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRouteImport.update(
    {
      id: '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId',
      path: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId',
      getParentRoute: () => AppRoute,
    } as any,
  )
const AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRouteImport.update(
    {
      id: '/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId',
      path: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId',
      getParentRoute: () => AppRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/chat': typeof AppChatRoute
  '/common-tasks': typeof AppCommonTasksRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof AppWorkspacesCreateRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/projects/$projectId/orchestrator-prompt': typeof AppProjectsProjectIdOrchestratorPromptRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof AppHostsHostIdWorkspacesCreateRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/projects/$projectId/speckit/$featureId': typeof AppProjectsProjectIdSpeckitFeatureIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/chat': typeof AppChatRoute
  '/common-tasks': typeof AppCommonTasksRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof AppWorkspacesCreateRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/projects/$projectId/orchestrator-prompt': typeof AppProjectsProjectIdOrchestratorPromptRoute
  '/hosts/$hostId/workspaces/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/hosts/$hostId/workspaces/create': typeof AppHostsHostIdWorkspacesCreateRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/projects/$projectId/speckit/$featureId': typeof AppProjectsProjectIdSpeckitFeatureIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/common-tasks': typeof AppCommonTasksRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/workspaces_/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/_app/workspaces_/create': typeof AppWorkspacesCreateRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/_app/hosts/$hostId/workspaces': typeof AppHostsHostIdWorkspacesRoute
  '/_app/projects/$projectId_/orchestrator-prompt': typeof AppProjectsProjectIdOrchestratorPromptRoute
  '/_app/hosts/$hostId/workspaces_/$workspaceId': typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  '/_app/hosts/$hostId/workspaces_/create': typeof AppHostsHostIdWorkspacesCreateRoute
  '/_app/projects/$projectId_/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/_app/projects/$projectId_/speckit/$featureId': typeof AppProjectsProjectIdSpeckitFeatureIdRoute
  '/hosts/$hostId/workspaces/$workspaceId/vscode': typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
  '/_app/projects/$projectId_/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/chat'
    | '/common-tasks'
    | '/workspaces'
    | '/projects/$projectId'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/$workspaceId/vscode'
    | '/hosts/$hostId/workspaces'
    | '/projects/$projectId/orchestrator-prompt'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/projects/$projectId/issues/$issueId'
    | '/projects/$projectId/speckit/$featureId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
    | '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/chat'
    | '/common-tasks'
    | '/workspaces'
    | '/projects/$projectId'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/$workspaceId/vscode'
    | '/hosts/$hostId/workspaces'
    | '/projects/$projectId/orchestrator-prompt'
    | '/hosts/$hostId/workspaces/$workspaceId'
    | '/hosts/$hostId/workspaces/create'
    | '/projects/$projectId/issues/$issueId'
    | '/projects/$projectId/speckit/$featureId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
    | '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/chat'
    | '/_app/common-tasks'
    | '/_app/workspaces'
    | '/_app/projects/$projectId'
    | '/_app/workspaces_/$workspaceId'
    | '/_app/workspaces_/create'
    | '/workspaces/$workspaceId/vscode'
    | '/_app/hosts/$hostId/workspaces'
    | '/_app/projects/$projectId_/orchestrator-prompt'
    | '/_app/hosts/$hostId/workspaces_/$workspaceId'
    | '/_app/hosts/$hostId/workspaces_/create'
    | '/_app/projects/$projectId_/issues/$issueId'
    | '/_app/projects/$projectId_/speckit/$featureId'
    | '/hosts/$hostId/workspaces/$workspaceId/vscode'
    | '/_app/projects/$projectId_/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId'
    | '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId'
    | '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  WorkspacesWorkspaceIdVscodeRoute: typeof WorkspacesWorkspaceIdVscodeRoute
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/common-tasks': {
      id: '/_app/common-tasks'
      path: '/common-tasks'
      fullPath: '/common-tasks'
      preLoaderRoute: typeof AppCommonTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/workspaces/$workspaceId/vscode': {
      id: '/workspaces/$workspaceId/vscode'
      path: '/workspaces/$workspaceId/vscode'
      fullPath: '/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof WorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces_/create': {
      id: '/_app/workspaces_/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof AppWorkspacesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces_/$workspaceId': {
      id: '/_app/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/orchestrator-prompt': {
      id: '/_app/projects/$projectId_/orchestrator-prompt'
      path: '/projects/$projectId/orchestrator-prompt'
      fullPath: '/projects/$projectId/orchestrator-prompt'
      preLoaderRoute: typeof AppProjectsProjectIdOrchestratorPromptRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts/$hostId/workspaces': {
      id: '/_app/hosts/$hostId/workspaces'
      path: '/hosts/$hostId/workspaces'
      fullPath: '/hosts/$hostId/workspaces'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/hosts/$hostId/workspaces/$workspaceId/vscode': {
      id: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      path: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof HostsHostIdWorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId_/speckit/$featureId': {
      id: '/_app/projects/$projectId_/speckit/$featureId'
      path: '/projects/$projectId/speckit/$featureId'
      fullPath: '/projects/$projectId/speckit/$featureId'
      preLoaderRoute: typeof AppProjectsProjectIdSpeckitFeatureIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId': {
      id: '/_app/projects/$projectId_/issues/$issueId'
      path: '/projects/$projectId/issues/$issueId'
      fullPath: '/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts/$hostId/workspaces_/create': {
      id: '/_app/hosts/$hostId/workspaces_/create'
      path: '/hosts/$hostId/workspaces/create'
      fullPath: '/hosts/$hostId/workspaces/create'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hosts/$hostId/workspaces_/$workspaceId': {
      id: '/_app/hosts/$hostId/workspaces_/$workspaceId'
      path: '/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/workspaces/create/$draftId'
      path: '/projects/$projectId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId'
      path: '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId'
      path: '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/hosts/$hostId/workspaces/create/$draftId'
      path: '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/hosts/$hostId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/$workspaceId'
      path: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/hosts/$hostId/workspaces/create/$draftId'
      path: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/issues/$issueId/hosts/$hostId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppCommonTasksRoute: typeof AppCommonTasksRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppWorkspacesWorkspaceIdRoute: typeof AppWorkspacesWorkspaceIdRoute
  AppWorkspacesCreateRoute: typeof AppWorkspacesCreateRoute
  AppHostsHostIdWorkspacesRoute: typeof AppHostsHostIdWorkspacesRoute
  AppProjectsProjectIdOrchestratorPromptRoute: typeof AppProjectsProjectIdOrchestratorPromptRoute
  AppHostsHostIdWorkspacesWorkspaceIdRoute: typeof AppHostsHostIdWorkspacesWorkspaceIdRoute
  AppHostsHostIdWorkspacesCreateRoute: typeof AppHostsHostIdWorkspacesCreateRoute
  AppProjectsProjectIdIssuesIssueIdRoute: typeof AppProjectsProjectIdIssuesIssueIdRoute
  AppProjectsProjectIdSpeckitFeatureIdRoute: typeof AppProjectsProjectIdSpeckitFeatureIdRoute
  AppProjectsProjectIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute: typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppCommonTasksRoute: AppCommonTasksRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppWorkspacesWorkspaceIdRoute: AppWorkspacesWorkspaceIdRoute,
  AppWorkspacesCreateRoute: AppWorkspacesCreateRoute,
  AppHostsHostIdWorkspacesRoute: AppHostsHostIdWorkspacesRoute,
  AppProjectsProjectIdOrchestratorPromptRoute:
    AppProjectsProjectIdOrchestratorPromptRoute,
  AppHostsHostIdWorkspacesWorkspaceIdRoute:
    AppHostsHostIdWorkspacesWorkspaceIdRoute,
  AppHostsHostIdWorkspacesCreateRoute: AppHostsHostIdWorkspacesCreateRoute,
  AppProjectsProjectIdIssuesIssueIdRoute:
    AppProjectsProjectIdIssuesIssueIdRoute,
  AppProjectsProjectIdSpeckitFeatureIdRoute:
    AppProjectsProjectIdSpeckitFeatureIdRoute,
  AppProjectsProjectIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute:
    AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute,
  AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdHostsHostIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute:
    AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesWorkspaceIdRoute,
  AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdIssuesIssueIdHostsHostIdWorkspacesCreateDraftIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  WorkspacesWorkspaceIdVscodeRoute: WorkspacesWorkspaceIdVscodeRoute,
  HostsHostIdWorkspacesWorkspaceIdVscodeRoute:
    HostsHostIdWorkspacesWorkspaceIdVscodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
